### ISSUE TITLE
Bot does not want to play radio station if there is no song played before

### ISSUE THREAD

**Issue by kuskoman** [kuskoman/dumbot#16]
Log: 
`
Joined channel 565296990028693544
(node:4964) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'end' of undefined
    at SoundPlayer.play (/home/ubuntu/dumbot/dist/modules/soundPlayer/player.js:31:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Joined channel 565296990028693544
(node:4964) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'end' of undefined
    at SoundPlayer.play (/home/ubuntu/dumbot/dist/modules/soundPlayer/player.js:31:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
`

**Comment by kuskoman** [comment]
Probably the reason is calling `this.dispatcher.end();` when dispatcher is undefined
